### PR TITLE
Add "internal" to go-debian subpackages

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Without this, `pault.ag/go/debian/internal` as an import _technically_ doesn't exist. :smile:

**Comment by tianon** [comment]
(Also, godoc is reasonably sane regarding this: https://godoc.org/github.com/paultag/go-debian/internal)

**Comment by paultag** [comment]
Hunh, OK. I need to do this to the json file on my machine

**Comment by paultag** [comment]
fixed on my server; merging

**Pull request merged**
